# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    templates:
      - docs-on-readthedocs
    vars:
      rtd_project_name: 'airship-treasuremap'
      rtd_webhook_id: '47687'
    check:
      jobs:
        - treasuremap-seaworthy-site-lint
        - treasuremap-seaworthy-virt-site-lint
        - treasuremap-airskiff-ubuntu-site-lint
        - treasuremap-airskiff-suse-site-lint
        - treasuremap-airsloop-site-lint
        - treasuremap-aiab-site-lint
        # TODO
        # update OSH charts vaoues in manifests and add more
        # charts to full-site manifests
        # - treasuremap-airskiff-multinode-full-site
        # 1node airskiff jobs disabled becase of frequent overload issues
        # - treasuremap-airskiff-1node-reduced-site
        # - treasuremap-airskiff-1node-reduced-site-armada-operator
        - treasuremap-airskiff-5nodes-reduced-site
        - treasuremap-airskiff-5nodes-reduced-site-armada-operator
        # - maas-airskiff-deployment-noble-kubeadm-maas-upgrade
    gate:
      jobs:
        - treasuremap-seaworthy-site-lint
        - treasuremap-seaworthy-virt-site-lint
        - treasuremap-airskiff-ubuntu-site-lint
        - treasuremap-airskiff-suse-site-lint
        - treasuremap-airsloop-site-lint
        - treasuremap-aiab-site-lint
    post:
      jobs:
        - treasuremap-upload-git-mirror
    promote:
      jobs:
        - promote-airship-project-docs:
            files:
              - ^doc/.*$

- nodeset:
    name: treasuremap-single-node-ubuntu-noble
    nodes:
      - name: ubuntu-noble
        label: ubuntu-noble

- nodeset:
    name: treasuremap-single-node-ubuntu-jammy
    nodes:
      - name: ubuntu-jammy
        label: ubuntu-jammy

- nodeset:
    name: treasuremap-airskiff-5nodes-ubuntu_jammy
    nodes:
      - name: primary
        label: ubuntu-jammy
      - name: node-1
        label: ubuntu-jammy
      - name: node-2
        label: ubuntu-jammy
      - name: node-3
        label: ubuntu-jammy
      - name: node-4
        label: ubuntu-jammy
    groups:
      - name: primary
        nodes:
          - primary
      - name: nodes
        nodes:
          - node-1
          - node-2
          - node-3
          - node-4
      - name: k8s_cluster
        nodes:
          - primary
          - node-1
          - node-2
          - node-3
          - node-4
      - name: k8s_control_plane
        nodes:
          - primary
      - name: k8s_nodes
        nodes:
          - node-1
          - node-2
          - node-3
          - node-4


- nodeset:
    name: treasuremap-airskiff-5nodes-ubuntu_noble
    nodes:
      - name: primary
        label: ubuntu-noble
      - name: node-1
        label: ubuntu-noble
      - name: node-2
        label: ubuntu-noble
      - name: node-3
        label: ubuntu-noble
      - name: node-4
        label: ubuntu-noble
    groups:
      - name: primary
        nodes:
          - primary
      - name: nodes
        nodes:
          - node-1
          - node-2
          - node-3
          - node-4
      - name: k8s_cluster
        nodes:
          - primary
          - node-1
          - node-2
          - node-3
          - node-4
      - name: k8s_control_plane
        nodes:
          - primary
      - name: k8s_nodes
        nodes:
          - node-1
          - node-2
          - node-3
          - node-4

- nodeset:
    name: treasuremap-airskiff-3nodes-ubuntu_jammy
    nodes:
      - name: primary
        label: ubuntu-jammy
      - name: node-1
        label: ubuntu-jammy
      - name: node-2
        label: ubuntu-jammy
    groups:
      - name: primary
        nodes:
          - primary
      - name: nodes
        nodes:
          - node-1
          - node-2
      - name: k8s_cluster
        nodes:
          - primary
          - node-1
          - node-2
      - name: k8s_control_plane
        nodes:
          - primary
      - name: k8s_nodes
        nodes:
          - node-1
          - node-2


- nodeset:
    name: treasuremap-airskiff-3nodes-ubuntu_noble
    nodes:
      - name: primary
        label: ubuntu-noble
      - name: node-1
        label: ubuntu-noble
      - name: node-2
        label: ubuntu-noble
    groups:
      - name: primary
        nodes:
          - primary
      - name: nodes
        nodes:
          - node-1
          - node-2
      - name: k8s_cluster
        nodes:
          - primary
          - node-1
          - node-2
      - name: k8s_control_plane
        nodes:
          - primary
      - name: k8s_nodes
        nodes:
          - node-1
          - node-2

- nodeset:
    name: treasuremap-airskiff-1node-ubuntu_jammy
    nodes:
      - name: primary
        label: ubuntu-jammy
    groups:
      - name: primary
        nodes:
          - primary
      - name: k8s_cluster
        nodes:
          - primary
      - name: k8s_control_plane
        nodes:
          - primary

- nodeset:
    name: treasuremap-airskiff-1node-ubuntu_noble
    nodes:
      - name: primary
        label: ubuntu-noble
    groups:
      - name: primary
        nodes:
          - primary
      - name: k8s_cluster
        nodes:
          - primary
      - name: k8s_control_plane
        nodes:
          - primary


- nodeset:
    name: treasuremap-airskiff-1node-32GB-ubuntu_jammy
    nodes:
      - name: primary
        # This label is available in vexxhost ca-ymq-1 region
        # The flavor v3-standard-8 in this particular region has
        # 32GB nodes. The number of such nodes is extremely limited.
        label: ubuntu-jammy-32GB
    groups:
      - name: primary
        nodes:
          - primary
      - name: k8s_cluster
        nodes:
          - primary
      - name: k8s_control_plane
        nodes:
          - primary

- nodeset:
    name: treasuremap-airskiff-1node-32GB-ubuntu_noble
    nodes:
      - name: primary
        # This label is available in vexxhost ca-ymq-1 region
        # The flavor v3-standard-8 in this particular region has
        # 32GB nodes. The number of such nodes is extremely limited.
        label: ubuntu-noble-32GB
    groups:
      - name: primary
        nodes:
          - primary
      - name: k8s_cluster
        nodes:
          - primary
      - name: k8s_control_plane
        nodes:
          - primary

- job:
    name: airship-docker-build-gate-base
    abstract: true
    timeout: 3600
    run: tools/gate/playbooks/airship-docker-image-build.yaml


- job:
    name: airship-chart-build-base
    abstract: true
    timeout: 3600
    run: ./tools/gate/playbooks/build-charts.yaml

- job:
    name: treasuremap-airskiff-infra-deploy-base
    abstract: true
    roles:
      - zuul: openstack/openstack-helm
      - zuul: zuul/zuul-jobs
    required-projects:
      - openstack/openstack-helm
      - openstack/openstack-helm-plugin
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^site/seaworthy/.*$
      - ^site/airsloop/.*$
      - ^site/aiab/.*$
    timeout: 10800
    pre-run:
      - tools/gate/playbooks/checkout-treasuremap-ref.yaml
      - tools/gate/playbooks/prepare-hosts.yaml
      - tools/gate/playbooks/mount-volumes.yaml
      - tools/gate/playbooks/deploy-env.yaml
      - tools/gate/playbooks/git-config.yaml
    run:
      - tools/gate/playbooks/airship-run-scripts.yaml
    post-run:
      - tools/gate/playbooks/osh-infra-collect-logs.yaml
    vars:
      docker:
        root_path: "/opt/ext_vol/docker"
      containerd:
        root_path: "/opt/ext_vol/containerd"
      loopback_setup: true
      loopback_device: /dev/loop100
      loopback_image: "/opt/ext_vol/openstack-helm/ceph-loop.img"
      ceph_osd_data_device: /dev/loop100
      floating_network_setup: false
      site: airskiff
      helm_version: "4.1.1"
      HELM_ARTIFACT_URL: https://get.helm.sh/helm-v4.1.1-linux-amd64.tar.gz
      HTK_COMMIT: d89bc42b57f8c2898520181550b5019dcf31c06f
      OSH_COMMIT: d89bc42b57f8c2898520181550b5019dcf31c06f
      USE_ARMADA_GO: false
      ENABLE_SLEEP: false
      overlay_network_setup: true
      metallb_setup: true
      gatewayapi_setup: true
      coredns_resolver_setup: true
      dnsmasq_extra_args: "--server=/minikube.internal/10.96.0.10 --server=/cluster.local/10.96.0.10 --server=/svc.cluster.local/10.96.0.10"
      DOCKER_REGISTRY: "control-plane.minikube.internal:5000"
      openstack_provider_gateway_setup: false
      osh_plugin_repo: "{{ zuul.project.src_dir }}/../../openstack/openstack-helm-plugin"
      osh_values_overrides_path: "{{ zuul.project.src_dir }}/../../openstack/openstack-helm/values_overrides"
      gate_scripts_relative_path: .
      gate_scripts:
        - ./tools/deployment/airskiff/developer/000-prepare-k8s.sh
        - ./tools/deployment/airskiff/developer/009-setup-apparmor.sh
        - ./tools/deployment/airskiff/developer/000-clone-dependencies.sh
        - ./tools/deployment/airskiff/developer/020-setup-client.sh
        - ./tools/deployment/airskiff/developer/015-make-all-charts.sh
        - ./tools/deployment/airskiff/developer/017-make-all-images.sh
        - ./tools/deployment/airskiff/developer/022-generate_security_keys.sh
        - ./tools/deployment/airskiff/developer/025-start-artifactory.sh
        - ./tools/deployment/airskiff/developer/026-reduce-site.sh
        - ./tools/deployment/airskiff/developer/027-enable-armada-operator.sh
        - ./tools/deployment/airskiff/common/sleep.sh
        - ./tools/deployment/airskiff/developer/030-armada-bootstrap.sh
        - ./tools/deployment/airskiff/developer/050-expose-airflow-ui.sh
        - ./tools/deployment/airskiff/developer/100-deploy-osh.sh
        - ./tools/deployment/airskiff/common/os-env.sh
        - ./tools/gate/wait-for-shipyard.sh
        - ./tools/deployment/airskiff/common/get-airflow-worker-logs.sh

- job:
    name: treasuremap-airskiff-multinode-full-site
    parent: treasuremap-airskiff-infra-deploy-base
    nodeset: treasuremap-airskiff-5nodes-ubuntu_noble
    description: |
      Deploy Openstack using Airskiff and latest Treasuremap changes.
      Airskiff is using latest Airship v1.x based on Airflow-3.1.5
    voting: true
    vars:
      overlay_network_setup: true

- job:
    name: treasuremap-airskiff-5nodes-reduced-site
    parent: treasuremap-airskiff-infra-deploy-base
    nodeset: treasuremap-airskiff-5nodes-ubuntu_noble
    description: |
      Deploy Openstack using Airskiff and latest Treasuremap changes.
      Airskiff is using latest Airship v1.x based on Airflow-3.1.5
    voting: true
    vars:
      USE_ARMADA_GO: false

- job:
    name: treasuremap-airskiff-1node-reduced-site
    parent: treasuremap-airskiff-infra-deploy-base
    nodeset: treasuremap-airskiff-1node-ubuntu_noble
    description: |
      Deploy Openstack using Airskiff and latest Treasuremap changes.
      Airskiff is using latest Airship v1.x based on Airflow-3.1.5
    voting: true
    vars:
      USE_ARMADA_GO: false

- job:
    name: treasuremap-airskiff-1node-reduced-site-armada-operator
    parent: treasuremap-airskiff-infra-deploy-base
    nodeset: treasuremap-airskiff-1node-ubuntu_noble
    description: |
      Deploy Openstack using Airskiff and latest Treasuremap changes.
      Airskiff is using latest Airship v1.x based on Airflow-3.1.5
    voting: true
    vars:
      USE_ARMADA_GO: true

- job:
    name: treasuremap-airskiff-5nodes-reduced-site-armada-operator
    parent: treasuremap-airskiff-infra-deploy-base
    nodeset: treasuremap-airskiff-5nodes-ubuntu_noble
    description: |
      Deploy Openstack using Airskiff and latest Treasuremap changes.
      Airskiff is using latest Airship v1.x based on Airflow-3.1.5
    voting: true
    vars:
      USE_ARMADA_GO: true

- job:
    name: treasuremap-airskiff-deploy-maas-drydock-base
    parent: treasuremap-airskiff-infra-deploy-base
    abstract: true
    description: |
      Deploy Openstack using Airskiff and latest Treasuremap changes.
      Airskiff is using latest Airship v1.x based on Airflow-3.1.5
    vars:
      ENABLE_SLEEP: false
      ENABLE_MAAS_UPGRADE: false
      USE_ARMADA_GO: true
      MAKE_MAAS_IMAGES: true
      DISTRO: ubuntu_noble
      DOCKER_REGISTRY: "control-plane.minikube.internal:5000"
      gate_scripts:
        - ./tools/deployment/airskiff/developer/000-prepare-k8s.sh
        - ./tools/deployment/airskiff/developer/009-setup-apparmor.sh
        - ./tools/deployment/airskiff/developer/000-clone-dependencies.sh
        - ./tools/deployment/airskiff/developer/020-setup-client.sh
        - ./tools/deployment/airskiff/developer/015-make-all-charts.sh
        - ./tools/deployment/airskiff/developer/017-make-all-images.sh
        - ./tools/deployment/airskiff/developer/022-generate_security_keys.sh
        - ./tools/deployment/airskiff/developer/025-start-artifactory.sh
        - ./tools/deployment/airskiff/developer/026-reduce-site.sh
        - ./tools/deployment/airskiff/developer/027-enable-armada-operator.sh
        - ./tools/deployment/airskiff/developer/028-enable-maas-drydock.sh
        - ./tools/deployment/airskiff/developer/030-armada-bootstrap.sh
        - ./tools/deployment/airskiff/developer/050-expose-airflow-ui.sh
        - ./tools/deployment/airskiff/developer/100-deploy-osh.sh
        - ./tools/deployment/airskiff/common/os-env.sh
        - ./tools/gate/wait-for-shipyard.sh
        - ./tools/deployment/airskiff/common/get-airflow-worker-logs.sh
        - ./tools/deployment/airskiff/developer/200-upgrade-maas.sh
        - ./tools/deployment/airskiff/developer/000-sleep.sh


# - job:
#     name: maas-airskiff-deployment-noble-kubeadm-maas-upgrade
#     # Pinned for now due to Ansible 11 stopped verbosive output.
#     ansible-version: 9
#     description: |
#       Deploy maas using Airskiff and submitted Shipyard changes.
#     parent: treasuremap-airskiff-deploy-maas-drydock-base
#     nodeset: treasuremap-airskiff-5nodes-ubuntu_noble
#     required-projects:
#       - name: airship/treasuremap
#         override-checkout: v1.9
#     roles:
#       - zuul: airship/treasuremap
#     vars:
#       treasuremap_ref: v1.9
#       ENABLE_SLEEP: false
#       ENABLE_MAAS_UPGRADE: true
#       CLONE_MAAS: true
#       MAKE_MAAS_IMAGES: false
#       DISTRO: ubuntu_noble


- job:
    name: treasuremap-site-lint
    description:
      Lint a site using Pegleg. Default site is seaworthy.
    nodeset: treasuremap-single-node-ubuntu-noble
    timeout: 900
    pre-run:
      - tools/gate/playbooks/initial-setup.yaml
      - tools/gate/playbooks/git-config.yaml
    run: tools/gate/playbooks/site-lint.yaml
    vars:
      site: seaworthy
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$

- job:
    name: treasuremap-seaworthy-site-lint
    description: |
      Lint the seaworthy site using Pegleg.
    parent: treasuremap-site-lint
    vars:
      site: seaworthy
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^site/seaworthy-virt/.*$
      - ^site/airskiff/.*$
      - ^site/airsloop/.*$
      - ^site/aiab/.*$

- job:
    name: treasuremap-seaworthy-virt-site-lint
    description: |
      Lint the seaworthy site using Pegleg.
    parent: treasuremap-site-lint
    vars:
      site: seaworthy-virt
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^site/seaworthy/.*$
      - ^site/airskiff/.*$
      - ^site/airsloop/.*$
      - ^site/aiab/.*$

- job:
    name: treasuremap-airskiff-ubuntu-site-lint
    description: |
      Lint the airskiff site using Pegleg.
    parent: treasuremap-site-lint
    vars:
      site: airskiff
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^site/seaworthy/.*$
      - ^site/seaworthy-virt/.*$
      - ^site/airsloop/.*$
      - ^site/aiab/.*$

- job:
    name: treasuremap-airskiff-suse-site-lint
    description: |
      Lint the airskiff-suse site using Pegleg.
    parent: treasuremap-site-lint
    vars:
      site: airskiff-suse
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^site/seaworthy/.*$
      - ^site/seaworthy-virt/.*$
      - ^site/airsloop/.*$
      - ^site/aiab/.*$

- job:
    name: treasuremap-airsloop-site-lint
    description: |
      Lint the airsloop site using Pegleg.
    parent: treasuremap-site-lint
    vars:
      site: airsloop
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^site/seaworthy/.*$
      - ^site/seaworthy-virt/.*$
      - ^site/airskiff/.*$
      - ^site/aiab/.*$

- job:
    name: treasuremap-aiab-site-lint
    description: |
      Lint the aiab site using Pegleg.
    parent: treasuremap-site-lint
    pre-run:
      - tools/gate/playbooks/initial-setup.yaml
      - tools/gate/playbooks/generate-certs.yaml
    vars:
      site: aiab
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^site/seaworthy/.*$
      - ^site/seaworthy-virt/.*$
      - ^site/airskiff/.*$
      - ^site/airsloop/.*$

- job:
    name: treasuremap-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors airship/treasuremap to airshipit/treasuremap
    vars:
      git_mirror_repository: airshipit/treasuremap
    secrets:
      - name: git_mirror_credentials
        secret: treasuremap-airshipit-github-ed25519-secret-2026-01-13
        pass-to-parent: true

- secret:
    name: treasuremap-airshipit-github-ed25519-secret-2026-01-13
    data:
      user: git
      host: github.com
      host_key: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      ssh_key: !encrypted/pkcs1-oaep
        - ZoCBP21kF3a/+rDo0qBNLsggg+G5ZRfX1m7QkuAdDkgnaxLMvTfYlw0nTkcrshXDuJEoi
          kjHAiWc3gKAkQglEu1yNQFSdR0JECeMVvYpghYqPFNcY3Da2y2tbvhZZQbwU3QYnvk/CI
          t8OsYDSzCxusenFFqixta7iVwVo0M20TcCHccN0gNXkYvpzAXbmNJdVLAQ2oniDbI3Qpd
          VANrd1/fJCi//eNmADKg47Uv8xbV6MuLQupWwExUg/LZJ8bemttjHZjXn2ICCpUY1WUwz
          4VyRCiLjnaMKEvkspw5uRV3xiknp2a/SRqD7kuUdyThBRU9zAwdXCIZAyihOrm1xAggOH
          y3sgg7uTzLoFHJ0w7fLv5EOZ+1ikNPxvMelWM/UoH4D7Zm+HnvVbmoKRLngu3o9QajBeK
          gOArB7kqQKR4eXO3KDKRGubJ5tUnZhhXU22j5BIqZ3t0oxM/R68SUutYOqSGvinhiBbgY
          JXOooat6+XmI7HagH3tG+WRXjUYlIdViESFD9H+whgszuzHlHEfsgiT/voznneLgTn64W
          pOoSD96eIzSrHDjjEeWkEZz+0oTS8CPSUghGKxspaxW4iEn3U2lb6aDE21/05N7MEBeyq
          sM7ToI4KnrWGiRrbWWfwg0tuM5zoF+2zIQsLaRXX253U8aibpvNSDchLDWgkzc=
