---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-shipyard
  labels:
    name: ucp-shipyard-global
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.shipyard
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.shipyard
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.postgresql
      dest:
        path: .values.endpoints.postgresql_shipyard_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.postgresql
      dest:
        path: .values.endpoints.postgresql_airflow_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.postgresql_airflow_celery
      dest:
        path: .values.endpoints.postgresql_airflow_celery_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.shipyard
      dest:
        path: .values.endpoints.shipyard
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.airflow_oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_cache
      dest:
        path: .values.endpoints.oslo_cache

    # Database path
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.shipyard.postgres.database
      dest:
        path: .values.endpoints.postgresql_shipyard_db.path
        pattern: 'DB_NAME'
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.airflow.postgres.database
      dest:
        path: .values.endpoints.postgresql_airflow_db.path
        pattern: 'DB_NAME'
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.airflow.postgres.database
      dest:
        path: .values.endpoints.postgresql_airflow_celery_db.path
        pattern: 'DB_NAME'
    # Credentials
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.postgres.admin
      dest:
        path: .values.endpoints.postgresql_shipyard_db.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.postgres.admin
      dest:
        path: .values.endpoints.postgresql_airflow_db.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.postgres.admin
      dest:
        path: .values.endpoints.postgresql_airflow_celery_db.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.shipyard.postgres
      dest:
        path: .values.endpoints.postgresql_shipyard_db.auth.user
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.airflow.postgres
      dest:
        path: .values.endpoints.postgresql_airflow_db.auth.user
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.airflow.postgres
      dest:
        path: .values.endpoints.postgresql_airflow_celery_db.auth.user
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.airflow.oslo_messaging.user
      dest:
        path: .values.endpoints.oslo_messaging.auth.user
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.airflow.oslo_messaging.admin
      dest:
        path: .values.endpoints.oslo_messaging.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.shipyard.keystone
      dest:
        path: .values.endpoints.identity.auth.shipyard

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.postgresql_shipyard_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_postgres_admin_password
        path: .
    - dest:
        path: .values.endpoints.postgresql_airflow_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_postgres_admin_password
        path: .
    - dest:
        path: .values.endpoints.postgresql_airflow_celery_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_postgres_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.shipyard.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_shipyard_keystone_password
        path: .
    - dest:
        path: .values.endpoints.postgresql_shipyard_db.auth.user.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_shipyard_postgres_password
        path: .
    - dest:
        path: .values.endpoints.postgresql_airflow_db.auth.user.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_airflow_postgres_password
        path: .
    - dest:
        path: .values.endpoints.postgresql_airflow_celery_db.auth.user.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_airflow_postgres_password
        path: .
    - src:
        schema: deckhand/Passphrase/v1
        name: ucp_airflow_oslo_messaging_password
        path: .
      dest:
        path: .values.endpoints.oslo_messaging.auth.user.password
    - src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_messaging_password
        path: .
      dest:
        path: .values.endpoints.oslo_messaging.auth.admin.password
    # Airflow jwt secrets
    - dest:
        path: .values.conf.airflow.api_auth.jwt_secret
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_airflow_api_auth_jwt_secret
        path: .
    - dest:
        path: .values.conf.airflow.webserver.secret_key
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_airflow_api_auth_jwt_secret
        path: .
    - dest:
        path: .values.conf.airflow.core.fernet_key
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_airflow_core_fernet_key
        path: .
    - dest:
        path: .values.conf.shipyard.airflow.worker_log_jwt_secret
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_airflow_api_auth_jwt_secret
        path: .

data:
  chart_name: shipyard
  release: ucp-shipyard
  namespace: ucp
  wait:
    timeout: 600
    labels:
      release_group: airship-ucp-shipyard
    native:
      enabled: false
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-ucp-shipyard
  values:
    manifests:
      deployment_airflow_webserver_ui: true
      secret_apache_etc: true
      secret_airflow_webserver_ui: true
      service_airflow_webserver_ui: true
    endpoints:
      postgresql_airflow_db:
        name: postgresql
        hosts:
          default: postgresql
        path: /DB_NAME
        scheme: postgresql+psycopg2
        port:
          postgresql:
            default: 5432
        host_fqdn_override:
          default: null
      postgresql_shipyard_db:
        name: postgresql
        hosts:
          default: postgresql
        path: /DB_NAME
        scheme: postgresql+psycopg2
        port:
          postgresql:
            default: 5432
        host_fqdn_override:
          default: null
    prod_environment: true
    pod:
      replicas:
        shipyard:
          api: 2
        airflow:
          worker: 2
          # TODO: Scheduler can be set to 0 with a future version - here to
          # accommodate the upgrade to the current configuration with the
          # Scheduler being a sidecar with the Worker.
          scheduler: 0
    labels:
      job:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
    conf:
      shipyard:
        keystone_authtoken:
          memcache_security_strategy: None
      httpd: |
        ServerRoot "/usr/local/apache2"

        Listen 80

        LoadModule mpm_event_module modules/mod_mpm_event.so
        LoadModule authn_file_module modules/mod_authn_file.so
        LoadModule authn_core_module modules/mod_authn_core.so
        LoadModule authz_host_module modules/mod_authz_host.so
        LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
        LoadModule authz_user_module modules/mod_authz_user.so
        LoadModule authz_core_module modules/mod_authz_core.so
        LoadModule access_compat_module modules/mod_access_compat.so
        LoadModule auth_basic_module modules/mod_auth_basic.so
        LoadModule reqtimeout_module modules/mod_reqtimeout.so
        LoadModule filter_module modules/mod_filter.so
        LoadModule proxy_html_module modules/mod_proxy_html.so
        LoadModule log_config_module modules/mod_log_config.so
        LoadModule env_module modules/mod_env.so
        LoadModule headers_module modules/mod_headers.so
        LoadModule setenvif_module modules/mod_setenvif.so
        LoadModule version_module modules/mod_version.so
        LoadModule proxy_module modules/mod_proxy.so
        LoadModule proxy_connect_module modules/mod_proxy_connect.so
        LoadModule proxy_http_module modules/mod_proxy_http.so
        LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
        LoadModule remoteip_module modules/mod_remoteip.so
        LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
        LoadModule slotmem_plain_module modules/mod_slotmem_plain.so
        LoadModule unixd_module modules/mod_unixd.so
        LoadModule status_module modules/mod_status.so
        LoadModule autoindex_module modules/mod_autoindex.so

        <IfModule unixd_module>
        User daemon
        Group daemon
        </IfModule>

        <Directory />
            AllowOverride none
            Require all denied
        </Directory>

        <Files ".ht*">
            Require all denied
        </Files>

        ErrorLog /dev/stderr

        LogLevel warn

        <IfModule log_config_module>
            LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
            LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
            LogFormat "%h %l %u %t \"%r\" %>s %b" common

            <IfModule logio_module>
              LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
            </IfModule>

            SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
            CustomLog /dev/stdout common
            CustomLog /dev/stdout combined
            CustomLog /dev/stdout proxy env=forwarded
        </IfModule>

        <Directory "/usr/local/apache2/cgi-bin">
            AllowOverride None
            Options None
            Require all granted
        </Directory>

        <IfModule headers_module>
            RequestHeader unset Proxy early
        </IfModule>

        <IfModule proxy_html_module>
        Include conf/extra/proxy-html.conf
        </IfModule>

        <VirtualHost *:80>
          RemoteIPHeader X-Original-Forwarded-For

          ProxyPreserveHost On
          ProxyPass / http://localhost:8080/
          ProxyPassReverse / http://localhost:8080/

          <Proxy *>
              AuthName "Airflow"
              AuthType Basic
              AuthBasicProvider file
              AuthUserFile /usr/local/apache2/conf/.htpasswd
              Require valid-user
          </Proxy>
        </VirtualHost>
    logrotate:
      percent_max_log_fs_usage: 90
    network:
      airflow_webserver_ui:
        ingress:
          classes:
            namespace: "ucp-ingress"
            cluster: "ucp-ingress"
      shipyard:
        ingress:
          public: true
          classes:
            namespace: "ucp-ingress"
            cluster: "ucp-ingress"
          annotations:
            nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-body-size: "10m"
            nginx.ingress.kubernetes.io/configuration-snippet: |
              more_clear_headers "Server";
              more_set_headers "X-Content-Type-Options: 'nosniff'";
              more_set_headers "X-Frame-Options: 'deny'";
...
